### ISSUE TITLE
Networkx digraph_extend methods

### ISSUE THREAD

**Issue by gmattson92** [ProveMath/prove-math#6]
The nx.digraph_extend methods single_source_shortest_anydirectional_path_length and multiple_sources_shortest_path_length should get new names that give a more accurate idea of their functions.  These return the list of paths from a single (or multiple) node(s) to every other path-connected node, not just the length of some specific path.

We should also change how one of them works.  Currently single_source... will return paths in either direction, i.e. any neighbor of the input node.  Multiple_sources... returns only paths to descendants, not to ancestors.  We should make this uniform one way or the other so we don't run into any confusion later.

**Comment by MareoRaft** [comment]
The return value is a dictionary, where each key is a node and each value is the distance (or shortest path length) of that node from the source node.

Since "distance" implies "shortest path length", I propose:

single_source_anydirectional_distance_dictionary()
or just
anydirectional_distance_dictionary()

and

multiple_sources_distance_dictionary()
or just
distance_dictionary()

I prefer the shorter ones.  We can make them automatically support one or multiple sources, just like we are already doing in methods like predecessors(), ancestors(), etc, so we no longer need to say "single_source" or "multiple_sources".

**Comment by MareoRaft** [comment]
The use of "anydirectional" is not a mistake but on purpose.  One of them is "anydirectional" and meant to go both directions.  The other is not anydirectional, so in the context of a Digraph, it only goes forward.

**Comment by gmattson92** [comment]
These methods have been reworked a little and renamed.  They now exist as `relatives_to_distance_dict`, which returns ancestors and descendants of the input nodes, and `descendants_to_distance_dict` which returns only descendants.  Both methods can accommodate single or multiple inputs nodes.
